# config/config.yaml
# William L. Close
# Schloss Lab
# University of Michigan

# Purpose: Snakemake config file for viralMetagenomicsPipeline. 

##################################################################
#
# User-defined Settings
#
##################################################################

# Names of all the control samples for the viral metagenomic pipeline. Uncomment lines and add more as required.
# Ex: control read files named 140142_TATGCCAG-TTCCATTG_S154_R1_001.fastq.gz and 140142_TATGCCAG-TTCCATTG_S154_R2_001.fastq.gz.
metagenomeControls:
  # - 140142

# Number of bases to trim back from each read using Trimmomatic during quality control.
metagenomeHeadcrop: 15

# False-positive rate to use in VirFinder.
metagenomeVirfinderFpr: 0.05

# False-discovery rate to use in VirFinder.
metagenomeVirfinderFdr: 0.15

# Minimum number of reads to subsample to. Script will use smallest number of reads above this level.
metagenomeSubthresh: 2e5

# Alpha diversity (within sample) metrics to calculate in metagenomic pipeline.
metagenomeAlpha:
  - invsimpson
  - shannon
  - sobs

# Beta diversity (between sample) metrics to calculate in metagenomic pipeline.
metagenomeBeta:
  - bray





##################################################################
#
# Universal Settings (do NOT change)
#
##################################################################

# Sequence file read numbers.
readNum:
  - R1
  - R2

# Setting universal random seed.
seed: 20170415

# Different groups of output files generated by the metagenomic pipeline.
metagenomeGroups:
  - sample
  - control

# Wildcard for paired-ness of samples.
metagenomeReadSet:
  - R1_paired
  - R2_paired
  - unpaired

# Quality control reports to make.
metagenomeReports:
  - raw
  - trimmed
  - decon
  - assembly
